services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    container_name: ${CONTAINER_NAME}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
