services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    ports:
      - "86:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DB_URL}
      - RUN_MIGRATIONS=1
      - BASE_URL=${RSS_URL}
      - CREATE_ADMIN=0
      - ADMIN_USERNAME=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASS}
  db:
    image: postgres:17-alpine
    container_name: miniflux-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db:
