# Run with docker compose up -d
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8060:8080
    environment:
      - DOZZLE_REMOTE_AGENT=${REMOTE_AGENT}
      - DOZZLE_ENABLE_ACTIONS=true
